---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    - - forwarded_port
      - guest: 8080
        host: 8080
        auto_correct: true

provisioner:
  name: chef_zero
  data_path: test/shared
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: true
  attributes:
    jenkins:
      master:
        version: 1.643-1.1
        channel: current
    maven:
      install_java: false
    java:
      install_flavor: openjdk
      jdk_version: 8

platforms:
  - name: centos-6.8
    box: bento/centos-6.8
    run_list:
      - java::default
      - jenkins::master
  - name: centos-7.3
    box: bento/centos-7.3
    run_list:
      - java::default
      - jenkins::master


suites:
  # Smoke suite
  - name: smoke
    run_list: smoke::default

  # Artifactory suites
  - name: jenkins_plugins_artifactory_install
    run_list: jenkins_plugins_artifactory::install
  - name: jenkins_plugins_artifactory_configure
    run_list: jenkins_plugins_artifactory::configure
  - name: jenkins_plugins_artifactory_remove
    run_list: jenkins_plugins_artifactory::remove

  # Maven suites
  - name: jenkins_plugins_maven_install
    run_list: jenkins_plugins_maven::install
  - name: jenkins_plugins_maven_configure
    run_list: jenkins_plugins_maven::configure
  - name: jenkins_plugins_maven_remove
    run_list: jenkins_plugins_maven::remove

  # Git suites
  - name: jenkins_plugins_git_install
    run_list: jenkins_plugins_git::install
  - name: jenkins_plugins_git_configure
    run_list: jenkins_plugins_git::configure

  # SSH suites
  - name: jenkins_plugins_ssh_key_add
    run_list: jenkins_plugins_ssh_key::add
  - name: jenkins_plugins_ssh_key_update
    run_list: jenkins_plugins_ssh_key::update
  - name: jenkins_plugins_ssh_key_remove
    run_list: jenkins_plugins_ssh_key::remove

  - name: jenkins_plugins_ssh_config_add
    run_list: jenkins_plugins_ssh_config::add
  - name: jenkins_plugins_ssh_config_update
    run_list: jenkins_plugins_ssh_config::update
  - name: jenkins_plugins_ssh_config_remove
    run_list: jenkins_plugins_ssh_config::remove

  # Workflow suites
  - name: jenkins_plugins_workflow_create
    run_list: jenkins_plugins_workflow::create
  - name: jenkins_plugins_workflow_delete
    run_list: jenkins_plugins_workflow::delete
