name             'jenkins_plugins'
maintainer       'Monkey Little'
maintainer_email 'cookbooks@monkeylittle.com'
license          'MIT'
description      'Installs/Configures jenkins_plugins'
long_description 'Installs/Configures jenkins_plugins'
version          '0.1.0'

depends 'jenkins'
depends 'maven'
